### ISSUE TITLE
Missing videso

### ISSUE THREAD

**Issue by gyglim** [aliensunmin/DomainSpecificHighlight#3]
Hi 

There are several videos missing:
7zXaMZeJjho
dJdc1piq44U
s4it3_HVIr4
pvyy-j51M64
14Spx6Be41c
CnuWsFRRiUI
3Yig0olMgh8
YcD5_ZCfhfI
BV8xEXG16go
iAMGMz8-5rc
HXabA9I2h2M
eSE_2KkrQDw
A-5_6OH3IQ4
Pmfggm7ojlY
1EmrEluKmHY

Can you please reupload them?
Thanks a lot.

Regards,
Michael

**Comment by aliensunmin** [comment]
Hi Michael,

They should be there.
-MS

**Comment by gyglim** [comment]
Great, thank you very much.
